server:
  port: 8000

spring:
  application:
    name: cloud-order-service

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"


eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    ##是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #入住地址
      #      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: order8000
    prefer-ip-address: true # 访问路径可以显示ip
    # Eureka 客户端服务器发送心跳的时间间隔，单位秒-默认30
    lease-renewal-interval-in-seconds: 2
    # Eureka 服务端在收到最后一次心态后等待时间上限，单位为秒-默认90，超时将提出服务
    lease-expiration-duration-in-seconds: 1
