server:
  port: 8006 # 8006表示注册到consul服务器支付服务提供者的端口号

spring:
  application:
    name: cloud-provider-payment  # 服务别名，注册的zookeeper到注册中心名称
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
