server:
  port: 9002


eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为true
    register-with-eureka: true
    ##是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #入住地址
      #      defaultZone: http://localhost:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xshi0001/springcloudlearn.git
          search-paths:
            - springcloudlearn
      label: main
  # ========================= bus 总线 rabbitMq======================
  rabbitmq:
    host: 192.168.130.237
    port: 15672
    username: admin
    password: admin

management: # 暴露bus,刷新配置的端点
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
    #  curl -X POST "http://localhost:3344/actuator/bus-refresh"








