server:
  port: 8901

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应（已经上传nacos中配置）
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: 192.168.130.237:8848
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver  #5.X的选择这个
    url: jdbc:mysql://192.168.130.43:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Ffgewe2133%^332312a
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml

