server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #多个路由
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #          uri: http://localhost:8001   #匹配后提供服务的路由地址,此处是写死的
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由 url+Path=URL 即 http://localhost:8001/payment/get/**


        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates: # predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - After=2020-07-27T15:54:01.365+08:00[Asia/Shanghai]  # 请求生效时刻
            - Cookie=username,zzyy  # curl http://localhost:9527/payment/lb --cookie "username=zzyy" -H "X-Request-Id:10"
            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
            - Method=GET

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
