server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery: # 换成nginx的80端口做集群
        server-addr: 192.168.130.237:80 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
