server:
  port: 8004 # 8004表示注册到zookeeper服务器支付服务提供者的端口号

spring:
  application:
    name: cloud-payment-service  # 服务别名，注册的zookeeper到注册中心名称
  cloud:
    zookeeper:
      connect-string: 192.168.130.169:2181

